export const IPC_CHANNELS = {
  conversationsListProjects: 'conversations:listProjects',
  projectsPickFolder: 'projects:pickFolder',
  projectsReveal: 'projects:reveal',
  projectsOpenInEditor: 'projects:openInEditor',
  projectsCountLineChanges: 'projects:countLineChanges',
  linksOpen: 'links:open',
  filesSaveClipboardImage: 'files:saveClipboardImage',
  workspaceLoad: 'workspace:load',
  workspaceSave: 'workspace:save',
  sessionsOpen: 'sessions:open',
  sessionsWrite: 'sessions:write',
  sessionsResize: 'sessions:resize',
  sessionsClose: 'sessions:close',
  sessionsOutput: 'sessions:output',
  sessionsExit: 'sessions:exit',
  sessionsClaudeHook: 'sessions:claudeHook',
  sessionsStatus: 'sessions:status',
  integrationCheck: 'integration:check',
  integrationRepair: 'integration:repair',
  usageRead: 'usage:read',
  usageChanged: 'usage:changed',
  updatesRead: 'updates:read',
  updatesInstall: 'updates:install',
  updatesChanged: 'updates:changed',
} as const;
